title: Résumé
baseurl: "/resume"
exclude:
  - README.md
  - "resume-ys.md"
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - jekyll-crisp-minimal-resume.gemspec
  - /script
  - /screenshots
  - /fixtures
  - Rakefile
color: blue
